---
- name: Configure EC2 Instance
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      command: sudo yum install docker -y

    - name: Start Docker
      command: sudo systemctl start docker

    - name: Enable Docker on boot
      command: sudo systemctl enable docker
